[package]
name = "advent_of_code_scripts"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
reqwest = { version = "0.12.14", features = ["blocking", "cookies"] }
dotenv = "0.15"
